engines:
  eslint:
    enabled: true
    channel: eslint-3
    checks:
      complexity:
        enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  rubocop:
    enabled: true
exclude_paths:
- .DS_Store
- build/
- coverage/
- dist/
- node_modules/
- test/
- docs/
- .codeclimate.yml
- .eslintignore
- .eslintrc
- .gitignore
- .rubocop.yml
- .travis.yml
- files.json
- karma.conf.js
- LICENSE
- package.json
- npm-shrinkwrap.json
- README.md
ratings:
  paths:
  - lib/**
